// Generated by gencpp from file axis_camera/axis_ptz_cmd.msg
// DO NOT EDIT!


#ifndef AXIS_CAMERA_MESSAGE_AXIS_PTZ_CMD_H
#define AXIS_CAMERA_MESSAGE_AXIS_PTZ_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace axis_camera
{
template <class ContainerAllocator>
struct axis_ptz_cmd_
{
  typedef axis_ptz_cmd_<ContainerAllocator> Type;

  axis_ptz_cmd_()
    : pan(0.0)
    , tilt(0.0)
    , zoom(0.0)
    , speed(0.0)  {
    }
  axis_ptz_cmd_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)
    , zoom(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;

   typedef float _zoom_type;
  _zoom_type zoom;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct axis_ptz_cmd_

typedef ::axis_camera::axis_ptz_cmd_<std::allocator<void> > axis_ptz_cmd;

typedef boost::shared_ptr< ::axis_camera::axis_ptz_cmd > axis_ptz_cmdPtr;
typedef boost::shared_ptr< ::axis_camera::axis_ptz_cmd const> axis_ptz_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::axis_camera::axis_ptz_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace axis_camera

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'axis_camera': ['/home/iqr/Desktop/iqr_jackal/src/axis_camera/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df0a4a8164fa4150896f61e9db960933";
  }

  static const char* value(const ::axis_camera::axis_ptz_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf0a4a8164fa4150ULL;
  static const uint64_t static_value2 = 0x896f61e9db960933ULL;
};

template<class ContainerAllocator>
struct DataType< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "axis_camera/axis_ptz_cmd";
  }

  static const char* value(const ::axis_camera::axis_ptz_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Pan value\n\
float32 pan\n\
# Tilt value\n\
float32 tilt\n\
# Zoom value\n\
float32 zoom\n\
# Speed value\n\
float32 speed\n\
\n\
";
  }

  static const char* value(const ::axis_camera::axis_ptz_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
      stream.next(m.zoom);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct axis_ptz_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::axis_camera::axis_ptz_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::axis_camera::axis_ptz_cmd_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
    s << indent << "zoom: ";
    Printer<float>::stream(s, indent + "  ", v.zoom);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AXIS_CAMERA_MESSAGE_AXIS_PTZ_CMD_H
